scrape_configs:
  - job_name: 'main-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8083']

  - job_name: 'workload-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8084']